WINDOW_WIDTH = 1440
WINDOW_HEIGHT = 720

STORES = []
SHELVES = []

CATEGORY_NAMES = ['Empty', 'Unreachable']
CATEGORY_COLORS = ['white', 'red']

DEFAULT_SHELF_PREFIX = "Shelf "
DEFAULT_SHELF_WIDTH = 400
DEFAULT_SHELF_HEIGHT = 130
DEFAULT_SHELF_MARGIN = 150

DEFAULT_SPACE_MARGIN = 75