name: Deploy

on:
  push:
    branches:
      - refactor

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build app
        run: npm run build

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Refactor build
          branch: main
          file_pattern: 'build/*'
          commit_user_name: Jordi Marmi [GitHub Actions]
          commit_user_email: jordimarmi1@gmail.com
          commit_author: JGedff