name: Send to test

on:
  pull_request:
  push:
    branches:
      - refactor

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Get repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build app
        run: python ./build.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Refactor to test
          branch: tests
          file_pattern: 'app/*'
          commit_user_name: Jordi Marmi [GitHub Actions]
          commit_user_email: jordimarmi1@gmail.com
          commit_author: JGedff
