from app.utils.json import JsonManager

CAJSON = {
    "window_title": "Gestor",
    "add_store": "+ Afegir magatzem",
    "name_store": "Nom del magatzem",
    "store": "Magatzem ",
    "add_shelf": "Afegir prestatgeries",
    "create_store": "Crear magatzem",
    "go_back": "← Tornar enrere",
    "edit_categories": "⚙️ Editar categories",
    "shelf_question_1": "Quants espais té la prestatgeria?:",
    "shelf_question_2": "Es poden posar productes als dos costats de la prestatgeria?",
    "shelf_question_4": "Quants pisos té la prestatgeria?",
    "yes": "Sí",
    "no": "No",
    "category": "Categoria:",
    "category_name": "Nom de la categoria:",
    "category_color": "Color de la categoria:",
    "save": "Guardar",
    "select_color": "Elegeix un color",
    "add_category": "+ Afegir categoria",
    "cancel": "Cancel·la",
    "create": "Crear",
    "floor": "Pis: ",
    "shelf": "Prestatgeria ",
    "product": "Producte: ",
    "add_product": "+ Afegir producte",
    "no_product": "Sense producte",
    "name": "Nom",
    "category_has_product": "Aquesta categoría tindrà productes?",
    "log_in": "Iniciar sessió",
    "register": "Registrarse",
    "user_name": "🤖Nom d'usuari:",
    "password": "🔒Contrasenya:",
    "enter_user_name": "Escriu el teu nom d'usuari",
    "enter_password": "Escriu la teva contrasenya",
    "repeat_password": "🔐Torna a escriure la teva contrasenya:",
    "access_offline": "Sense connexió",
    "forgot_password": "Has oblidat la teva contrasenya?",
    "change_image": "Canvia la imatge",
    "default_image": "Posa la imatge per defecte"
}

ENJSON = {
    "window_title": "Manager",
    "add_store": "+ Add store",
    "name_store": "Name of the store:",
    "store": "Store ",
    "add_shelf": "Add shelf",
    "create_store": "Create store",
    "go_back": "← Go back",
    "edit_categories": "⚙️ Edit categories",
    "shelf_question_1": "How many spaces does the shelf have?:",
    "shelf_question_2": "Can you put products in both sides of the shelf?:",
    "shelf_question_4": "How many floors does the shelf have?:",
    "yes": "Yes",
    "no": "No",
    "category": "Category:",
    "category_name": "Category name:",
    "category_color": "Category color:",
    "save": "Save",
    "select_color": "Select color",
    "add_category": "+ Add category",
    "cancel": "Cancel",
    "create": "Create",
    "floor": "Floor: ",
    "shelf": "Shelf ",
    "product": "Product: ",
    "add_product": "+ Add product",
    "no_product": "Without product",
    "name": "Name",
    "category_has_product": "Will this category have products?",
    "log_in": "Log in",
    "register": "Register",
    "user_name": "🤖User name:",
    "password": "🔒Password:",
    "enter_user_name": "Enter your user name",
    "enter_password": "Enter your password",
    "repeat_password": "🔐Rewrite your password:",
    "access_offline": "Offilne",
    "forgot_password": "Forgot your password?",
    "change_image": "Change the image",
    "default_image": "Set default image"
}

ESJSON = {
    "window_title": "Gestor",
    "add_store": "+ Añadir almacén",
    "name_store": "Nombre del almacén",
    "store": "Almacén ",
    "add_shelf": "Añadir estantería",
    "create_store": "Crear almacén",
    "go_back": "← Volver atrás",
    "edit_categories": "⚙️ Editar categorias",
    "shelf_question_1": "¿Cuantos espacios tiene la estantería?:",
    "shelf_question_2": "¿Se pueden poner productos en ambos lados de la estantería?",
    "shelf_question_4": "¿Cuantos pisos tiene la estantería?",
    "yes": "Sí",
    "no": "No",
    "category": "Categoría:",
    "category_name": "Nombre de la categoría:",
    "category_color": "Color de la categoría:",
    "save": "Guardar",
    "select_color": "Elige un color",
    "add_category": "+ Añadir categoría",
    "cancel": "Cancelar",
    "create": "Crear",
    "floor": "Piso: ",
    "shelf": "Estantería ",
    "product": "Producto: ",
    "add_product": "+ Añadir producto",
    "no_product": "Sin producto",
    "name": "Nombre",
    "category_has_product": "¿Esta categoría tendrá productos?",
    "log_in": "Iniciar sesión",
    "register": "Registrarse",
    "user_name": "🤖Nombre de usuario:",
    "password": "🔒Contraseña:",
    "enter_user_name": "Escribe tu nombre de usuario:",
    "enter_password": "Escribe tu contraseña:",
    "repeat_password": "🔐Vuelve a escribir tu contraseña:",
    "access_offline": "Sin conexión",
    "forgot_password": "¿Olvidaste tu contraseña?",
    "change_image": "Cambia la imagen",
    "default_image": "Pon la imagen por defecto"
}

def test_getLanguage():
    assert JsonManager.getLanguage() == ENJSON
    
    assert JsonManager.getLanguage("English") == ENJSON
    assert JsonManager.getLanguage("Español") == ESJSON
    assert JsonManager.getLanguage("Català") == CAJSON

    assert JsonManager.getLanguage("UNEXISTENT") == ENJSON